name: CI Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  update-readme:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Update README.md
        shell: bash
        run: |
          echo -e "\n## Última actualización: $(date)" >> README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: actualizar README.md automáticamente [skip ci]" || echo "No hay cambios para subir"
          git push || echo "No se pudo realizar el push"

  validate-dev:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate DEV Secret
        shell: bash
        run: |
          if [ "$LOCAL_DEV_TOKEN" = "${{ secrets.DEV_TOKEN }}" ]; then
            echo "DEV Token validado correctamente."
          else
            echo "DEV Token no coincide."
            exit 1
          fi